// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1IMKulpzNPsSiyKD-J0V5kDsWXgLrW0o',
    appId: '1:273711208169:web:3bf4594a56e844ca384278',
    messagingSenderId: '273711208169',
    projectId: 'salon-587d5',
    authDomain: 'salon-587d5.firebaseapp.com',
    storageBucket: 'salon-587d5.firebasestorage.app',
    measurementId: 'G-NYEQQJ669T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Ri8eVCvuypUJ-4Qit6MJTuj1gJ194xs',
    appId: '1:273711208169:android:5f255d302864b023384278',
    messagingSenderId: '273711208169',
    projectId: 'salon-587d5',
    storageBucket: 'salon-587d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu1RMBRST39XYGgaSBuwXMAQsyiqQOE7Q',
    appId: '1:273711208169:ios:2658e67e148904c8384278',
    messagingSenderId: '273711208169',
    projectId: 'salon-587d5',
    storageBucket: 'salon-587d5.firebasestorage.app',
    iosBundleId: 'com.example.salonBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu1RMBRST39XYGgaSBuwXMAQsyiqQOE7Q',
    appId: '1:273711208169:ios:2658e67e148904c8384278',
    messagingSenderId: '273711208169',
    projectId: 'salon-587d5',
    storageBucket: 'salon-587d5.firebasestorage.app',
    iosBundleId: 'com.example.salonBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1IMKulpzNPsSiyKD-J0V5kDsWXgLrW0o',
    appId: '1:273711208169:web:cbc66620c2aa5446384278',
    messagingSenderId: '273711208169',
    projectId: 'salon-587d5',
    authDomain: 'salon-587d5.firebaseapp.com',
    storageBucket: 'salon-587d5.firebasestorage.app',
    measurementId: 'G-6QY96CEQ28',
  );
}
